services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-development}
      POSTGRES_DB: ${DATABASE_NAME:-healthflow}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-testing}
    ports:
      - '${DATABASE_PORT:-5432}:5432'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'

volumes:
  postgres_data:
  rabbitmq_data:
